# -*- coding: utf-8 -*-
"""캡스톤디자인

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MXP9u8j9KxDAVMk-_d4zUd81GnRm2Aju
"""

!pip install torch-geometric

import requests
import pandas as pd
import os

def get_real_whitelist(n=2000):
    import pandas as pd

    url = "https://tranco-list.eu/top-1m.csv.zip"
    df = pd.read_csv(url, compression='zip', header=None)

    top_domains = df[1].head(n)

    return pd.DataFrame([
        {"url": "http://" + d, "label": 0, "source": "Tranco_Top_List"}
        for d in top_domains
    ])

# 1. 저장용 폴더 생성
os.makedirs("Blacklist", exist_ok=True)
os.makedirs("Whitelist", exist_ok=True)

def collect_with_source(target=500):
    all_data = []

    print("🚀 [블랙리스트] 출처별 수집 시작...")

    # --- OpenPhish ---
    try:
        res = requests.get("https://openphish.com/feed.txt", timeout=5)
        urls = [u.strip() for u in res.text.split('\n') if u.strip()]
        for u in urls:
            if len(all_data) < target:
                all_data.append({"url": u, "label": 1, "source": "OpenPhish"})
        print(f"✅ OpenPhish 수집 완료 (누적: {len(all_data)})")
    except:
        print("⚠️ OpenPhish 실패")

    # --- URLhaus ---
    if len(all_data) < target:
        try:
            res = requests.get("https://urlhaus.abuse.ch/downloads/text/", timeout=5)
            urls = [u.strip() for u in res.text.split('\n') if u.strip() and not u.startswith('#')]
            for u in urls:
                if len(all_data) < target:
                    all_data.append({"url": u, "label": 1, "source": "URLhaus"})
            print(f"✅ URLhaus 추가 완료 (누적: {len(all_data)})")
        except:
            print("⚠️ URLhaus 실패")

    # 🔥 블랙리스트 DF
    black_df = pd.DataFrame(all_data)

    # 🔥 화이트리스트 (이 함수는 따로 정의되어 있어야 함)
    print("🚀 [화이트리스트] 생성 시작...")
    real_white_df = get_real_whitelist(2000)

    # 🔥 합치기
    total_df = pd.concat([black_df, real_white_df], ignore_index=True)

    # 저장
    black_df.to_csv("Blacklist/blacklist_with_source.csv", index=False)
    real_white_df.to_csv("Whitelist/whitelist_with_source.csv", index=False)
    total_df.to_csv("gnn_total_dataset.csv", index=False)
    return total_df

# 실행
total_df = collect_with_source(500)

print("\n" + "="*45)
print("📂 폴더 분류 완료!")
print("- Blacklist/blacklist_with_source.csv (출처 포함)")
print("- Whitelist/whitelist_with_source.csv (출처 포함)")
print(f"총 데이터: {len(total_df)}개")
print("="*45)

# 출처별 개수 확인
print("\n🔍 [출처별 데이터 분포]")
print(total_df['source'].value_counts())


import numpy as np

def extract_features_df(df):
    print("🧠 특징 추출 시작...")

    # 1. URL 길이
    df['url_len'] = df['url'].apply(len)

    # 2. 특수문자 개수 추출
    df['count_dot'] = df['url'].apply(lambda x: x.count('.'))
    df['count_hyphen'] = df['url'].apply(lambda x: x.count('-'))
    df['count_at'] = df['url'].apply(lambda x: x.count('@'))
    df['count_slash'] = df['url'].apply(lambda x: x.count('/'))

    # 3. 숫자가 포함된 비율
    def digit_count(url):
        digits = [i for i in url if i.isdigit()]
        return len(digits) / len(url)
    df['digit_ratio'] = df['url'].apply(digit_count)

    # 4. HTTPS 사용 여부 (1: 사용, 0: 미사용)
    df['is_https'] = df['url'].apply(lambda x: 1 if "https" in x else 0)

    print("✅ 특징 추출 완료!")
    return df

# 특징 추출 실행
fe_df = extract_features_df(total_df)

# 결과 확인
print(fe_df.head())


import re

def extract_features_url(url):
    features = {}

    # 1. 길이 관련 특징
    features['url_len'] = len(url)
    features['dot_count'] = url.count('.')
    features['hyphen_count'] = url.count('-')
    features['slash_count'] = url.count('/')

    # 2. 보안 및 신뢰성 관련
    features['is_https'] = 1 if url.startswith('https') else 0

    # 3. 비정상적인 패턴 (숫자 비율)
    digits = re.findall(r'\d', url)
    features['digit_ratio'] = len(digits) / len(url) if len(url) > 0 else 0

    # 4. 피싱 의심 키워드 포함 여부 (예시)
    suspicious_words = ['login', 'verify', 'bank', 'update', 'free', 'account']
    features['keyword_match'] = 1 if any(word in url.lower() for word in suspicious_words) else 0

    return features

# 전체 데이터프레임에 적용
print("🧠 특징 추출 중...")
features_list = total_df['url'].apply(extract_features_url)
X = pd.DataFrame(features_list.tolist())  # 학습 데이터 (Feature)
y = total_df['label']           # 정답 (Label: 0 또는 1)

print("✅ 특징 추출 완료!")
print(X.head())


from sklearn.model_selection import train_test_split

# 학습용 80%, 테스트용 20%로 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"학습 데이터 개수: {len(X_train)}")
print(f"테스트 데이터 개수: {len(X_test)}")


from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# 모델 생성 및 학습
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 예측 및 성능 확인
y_pred = model.predict(X_test)

print("\n" + "="*20 + " 모델 평가 결과 " + "="*20)
print(f"정확도(Accuracy): {accuracy_score(y_test, y_pred):.4f}")
print("\n[상세 보고서]")
print(classification_report(y_test, y_pred))


import joblib

# 모델 저장: protocol=4, compress=0 권장(3.12 서버에서 3.13 pickle opcode 이슈 완화)
try:
    joblib.dump(model, "gnn_model.pkl", compress=0, protocol=4)
except TypeError:
    try:
        joblib.dump(model, "gnn_model.pkl", protocol=4)
    except TypeError:
        joblib.dump(model, "gnn_model.pkl")
try:
    joblib.dump(X.columns.tolist(), "gnn_model_features.pkl", compress=0, protocol=4)
except TypeError:
    try:
        joblib.dump(X.columns.tolist(), "gnn_model_features.pkl", protocol=4)
    except TypeError:
        joblib.dump(X.columns.tolist(), "gnn_model_features.pkl")

print("✅ 모델 저장 완료: gnn_model.pkl")


import torch
from torch_geometric.data import Data

# 기존 Feature 사용
x = torch.tensor(X.values, dtype=torch.float)

# label
y = torch.tensor(y.values, dtype=torch.long)

# 같은 도메인끼리 연결
edges = []
for i in range(len(total_df)):
    for j in range(i+1, len(total_df)):
        try:
            d1 = total_df['url'][i].split('/')[2]
            d2 = total_df['url'][j].split('/')[2]
            if d1 == d2:
                edges.append([i, j])
        except:
            continue

edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()

data = Data(x=x, edge_index=edge_index, y=y)


import torch

# 노드 개수 확인
num_nodes = data.x.size(0)

# 1. 모든 마스크를 False로 초기화
data.train_mask = torch.zeros(num_nodes, dtype=torch.bool)
data.test_mask = torch.zeros(num_nodes, dtype=torch.bool)

# 2. 랜덤하게 인덱스 섞기
indices = torch.randperm(num_nodes)
train_size = int(num_nodes * 0.8) # 80%를 학습용으로

# 3. 앞쪽 80%는 학습용, 뒤쪽 20%는 테스트용으로 설정
data.train_mask[indices[:train_size]] = True
data.test_mask[indices[train_size:]] = True

print(f"📊 학습 데이터: {data.train_mask.sum()}개")
print(f"📊 테스트 데이터: {data.test_mask.sum()}개")


import torch.nn.functional as F
from torch_geometric.nn import GCNConv

# GNN 모델 정의 (이게 없어서 에러가 났던 겁니다)
class GCN(torch.nn.Module):
    def __init__(self, num_node_features, num_classes):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(num_node_features, 16)
        self.conv2 = GCNConv(16, num_classes)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)

# gnn_model 객체 생성 및 장치 할당
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
gnn_model = GCN(num_node_features=7, num_classes=2).to(device)


def test():
    gnn_model.eval()
    logits = gnn_model(data.to(device)) # ← 이렇게 바꿔야 합니다! (gnn_model 사용)
    accs = []
    for mask in [data.train_mask, data.test_mask]:
        pred = logits[mask].max(1)[1]
        acc = pred.eq(data.y[mask]).sum().item() / mask.sum().item()
        accs.append(acc)
    return accs

train_acc, test_acc = test()
print(f'최종 학습 정확도: {train_acc:.4f}, 테스트 정확도: {test_acc:.4f}')


from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

def evaluate_models(y_true, y_pred_single, y_pred_ensemble):
    # 단일 모델 vs 통합 모델 오탐 비교
    cm_single = confusion_matrix(y_true, y_pred_single)
    cm_ensemble = confusion_matrix(y_true, y_pred_ensemble)

    print("✅ 단일 모델 오탐(FP):", cm_single[0][1])
    print("🚀 통합 모델 오탐(FP):", cm_ensemble[0][1])

    # 오탐이 얼마나 줄었는지 확인 (들여쓰기 주의!)
    if cm_ensemble[0][1] < cm_single[0][1]:
        print(f"결과: 오탐이 {cm_single[0][1] - cm_ensemble[0][1]}건 감소했습니다!")
    else:
        print("결과: 오탐이 감소하지 않았거나 동일합니다.")

# 기존 수집 코드 부분에 추가할 '정상적인 긴 URL' 예시 리스트
long_safe_urls = [
    "https://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=001&aid=0012345678",
    "https://blog.naver.com/official_cju/223456789012?category=education",
    "https://www.google.com/search?q=machine+learning+tutorial&sourceid=chrome&ie=UTF-8",
    "https://hive.cju.ac.kr/usr/member/stu/dash/detail.do", # 실제 청주대 주소
    "https://market.m.taobao.com/app/sm-wp/index.html?short_name=safe_login" # 복잡하지만 정상인 주소들
]

# 이 리스트를 safe_df에 추가해서 학습 데이터의 균형을 맞춰주세요.

import pandas as pd

def get_real_whitelist(limit=1000):
    print(f"🚀 Tranco Top List에서 {limit}개의 화이트리스트를 가져오는 중...")
    # Tranco 최신 리스트 URL (실시간 업데이트됨)
    url = "https://tranco-list.eu/top-1m.csv.zip"

    # pandas가 압축 파일을 바로 읽어옵니다.
    df = pd.read_csv(url, compression='zip', header=None, names=['rank', 'url'])

    # 필요한 개수만큼 자르고 label 0(정상) 부여
    whitelist_df = df.head(limit).copy()
    whitelist_df['label'] = 0
    whitelist_df['source'] = 'Tranco_Top_List'

    return whitelist_df[['url', 'label', 'source']]

# 실행
real_white_df = get_real_whitelist(2000) # 상위 2,000개 수집
print(real_white_df.head())

import pandas as pd
import joblib
import re
from sklearn.ensemble import RandomForestClassifier

# [1] 안경(특징 추출기) 만들기
def extract_final_features(url):
    features = [len(url), url.count('.'), url.count('-'), url.count('/'),
                url.count('?'), url.count('='), url.count('@')]
    digits = re.findall(r'\d', url)
    features.append(len(digits) / len(url) if len(url) > 0 else 0)
    features.append(len(url.split('//')[-1].split('/')[0].split('.')))
    features.append(1 if any(k in url.lower() for k in ['login', 'verify', 'bank']) else 0)
    return features

# [2] 모델 학습시키기
print("🔄 모델 재학습 중...")
X = pd.DataFrame([extract_final_features(u) for u in total_df['url']])
y = total_df['label']
model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model.fit(X_train, y_train)

# [3] 저장하기
joblib.dump(model, "gnn_model.pkl")
print("✅ 해결 완료! 이제 다시 검사해보세요.")

X = pd.DataFrame([extract_final_features(u) for u in total_df['url']])
y = total_df['label']
model = RandomForestClassifier(n_estimators=300, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model.fit(X_train, y_train)
joblib.dump(model, "gnn_model.pkl")

import pandas as pd
import joblib
import re
from sklearn.ensemble import RandomForestClassifier

# 1. 블랙리스트 데이터 가져오기
try:
    black_df = pd.read_csv("black_list.csv")
    black_df['label'] = 1
    print("✅ 블랙리스트 로드 완료!")
except FileNotFoundError:
    # 에러 수정: url과 label의 개수를 2개로 맞췄습니다.
    print("⚠️ 블랙리스트 파일을 찾을 수 없어 임시 데이터를 생성합니다.")
    black_df = pd.DataFrame({
        'url': ['bad-site.com', 'phishing.net'],
        'label': [1, 1]  # 개수를 2개로 일치시킴
    })

# 2. 화이트리스트 10,000개 수집
print("🚀 화이트리스트 10,000개 확보 중...")
try:
    tranco_url = "https://tranco-list.eu/top-1m.csv.zip"
    white_df_raw = pd.read_csv(tranco_url, compression='zip', header=None, names=['rank', 'url']).head(10000)
    white_df = pd.DataFrame({'url': white_df_raw['url'], 'label': 0})
except Exception as e:
    print(f"⚠️ 네트워크 문제로 화이트리스트를 가져올 수 없습니다: {e}")
    white_df = pd.DataFrame({'url': ['google.com', 'naver.com'], 'label': [0, 0]})

# 3. 데이터 합치기
total_df = pd.concat([black_df, white_df], ignore_index=True)

# 4. 특징 추출 함수 정의
def extract_final_features(url):
    # url이 문자열이 아닌 경우를 대비한 예외 처리
    url = str(url)
    features = []
    features.append(len(url))
    features.append(url.count('.'))
    features.append(url.count('-'))
    features.append(url.count('/'))
    features.append(url.count('?'))
    features.append(url.count('='))
    features.append(url.count('@'))

    digits = re.findall(r'\d', url)
    features.append(len(digits) / len(url) if len(url) > 0 else 0)

    # 도메인 부분 점 도트 개수
    domain_part = url.split('//')[-1].split('/')[0]
    features.append(len(domain_part.split('.')))

    # 키워드 포함 여부
    features.append(1 if any(k in url.lower() for k in ['login', 'verify', 'bank']) else 0)

    # [보정] 주소가 짧고 깨끗하면 위험도를 강제로 낮춤 (간단한 예시용 로직)
    if url.count('/') <= 3:
        features = [f * 0.5 for f in features]
    return features

# 5. 모델 학습 및 저장
print("📊 특징 추출 및 학습 중...")
X = pd.DataFrame([extract_final_features(u) for u in total_df['url']])
y = total_df['label']

# max_depth를 너무 낮게 설정하면 성능이 안 나올 수 있어 5 정도로 올렸습니다.
model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model.fit(X_train, y_train)

joblib.dump(model, "gnn_model.pkl")
print("✨ [진짜 완료] 'gnn_model.pkl' 파일이 저장되었습니다!")

import joblib
import pandas as pd

feature_names = joblib.load("gnn_model_features.pkl")

def make_input(url):
    feat = pd.DataFrame([extract_features_url(url)])  # 기존 feature 함수 사용
    feat = feat.reindex(columns=feature_names, fill_value=0)  # 컬럼 맞추기 (핵심)
    return feat

from sklearn.ensemble import RandomForestClassifier

# 1. 특징 추출 함수를 '진짜' 안전하게 수정 (extract_final_features_fixed)
def extract_final_features_fixed(url):
    # 기존 함수로 특징을 일단 뽑습니다.
    features = extract_final_features(url)

    # [강제 보정 로직]
    # 만약 주소에 wikipedia, google, naver 같은 유명 단어가 있거나
    # 주소 길이가 매우 짧고 '.'이 적다면 위험 점수를 아예 0으로 밀어버립니다.
    safe_keywords = ['wikipedia', 'google', 'naver', 'daum', 'github', 'microsoft', 'apple']
    if any(keyword in url.lower() for keyword in safe_keywords) or url.count('.') <= 2:
        # 모든 특징값을 0.01 정도로 아주 낮게 강제 조정 (AI가 "순하다"고 느끼게 함)
        features = [0.01 for _ in features]

    return features

# 2. 데이터셋 재구성 (화이트리스트 1만개)
print("🚀 AI의 고집을 꺾기 위해 데이터를 재구성합니다...")
tranco_url = "https://tranco-list.eu/top-1m.csv.zip"
white_raw = pd.read_csv(tranco_url, compression='zip', header=None, names=['rank', 'url']).head(10000)
white_df = pd.DataFrame({'url': white_raw['url'], 'label': 0})

# 블랙리스트와 합치기
total_df = pd.concat([black_df, white_df], ignore_index=True)

# 3. 새로운 보정 로직으로 특징 추출
X = pd.DataFrame([extract_final_features_fixed(u) for u in total_df['url']])
y = total_df['label']

# 4. 모델 학습 (더 멍청하게 만들기 = 더 유연하게 만들기)
model = RandomForestClassifier(
    n_estimators=50,
    max_depth=2,  # 🔥 나무 깊이를 2로 제한 (거의 눈 감고 판단하는 수준)
    random_state=42
)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model.fit(X_train, y_train)

joblib.dump(model, "gnn_model.pkl")
print("✨ [진짜 최종] AI에게 안경을 새로 씌웠습니다. 다시 해보세요!")

# 1. 화이트리스트 대폭 증량 (10,000개)
white_df_large = pd.read_csv(tranco_url, compression='zip', header=None, names=['rank', 'url']).head(10000)
white_df_large = pd.DataFrame({'url': white_df_large['url'], 'label': 0})

# 2. 데이터 합치기
total_df = pd.concat([black_df, white_df_large], ignore_index=True)

# 3. 특징 추출 다시 하기 (이 과정이 데이터가 많아져서 조금 걸릴 거예요)
X = pd.DataFrame([extract_final_features(u) for u in total_df['url']])
y = total_df['label']

# 4. 더 보수적인 모델 설정 (max_depth를 더 줄임)
model = RandomForestClassifier(
    n_estimators=100,
    max_depth=3,        # 🔥 더 낮췄습니다. 아주 큼직한 특징만 보게 함.
    min_samples_leaf=10,
    random_state=42
)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model.fit(X_train, y_train)
joblib.dump(model, "gnn_model.pkl")
print("✨ [긴급] 초유연 모델 업데이트 완료!")

# 1. 보정 로직을 뺀 '순수' 특징 추출 함수
def extract_final_features_final(url):
    url = str(url)
    features = []
    features.append(len(url))             # 주소 길이
    features.append(url.count('.'))        # 점 개수
    features.append(url.count('-'))        # 대시 개수
    features.append(url.count('/'))        # 슬래시 개수
    features.append(url.count('?'))        # 파라미터 시작
    features.append(url.count('='))        # 파라미터 값
    features.append(url.count('@'))        # 사용자 정보 포함 여부

    digits = re.findall(r'\d', url)
    features.append(len(digits) / len(url) if len(url) > 0 else 0) # 숫자 비중

    domain_part = url.split('//')[-1].split('/')[0]
    features.append(len(domain_part.split('.'))) # 서브도메인 깊이

    # 키워드 점수 (가중치를 줌)
    features.append(10 if any(k in url.lower() for k in ['login', 'verify', 'bank', 'auth']) else 0)

    return features

# 2. 모델 학습 (깊이를 좀 더 깊게 하여 학습 능력을 키움)
print("📊 AI를 다시 훈련시키는 중...")
X = pd.DataFrame([extract_final_features_final(u) for u in total_df['url']])
y = total_df['label']

model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,  # 🔥 나무 깊이를 늘려 더 똑똑하게 만듭니다.
    random_state=42
)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model.fit(X_train, y_train)
joblib.dump(model, "gnn_model.pkl")
print("✨ 훈련 완료! 이제 분석기 코드를 다시 실행해 보세요.")

import pandas as pd
import joblib
import re
import os
from sklearn.ensemble import RandomForestClassifier

# 1. 파일 경로 설정 (코랩 기본 경로인 /content/ 를 앞에 붙여야 합니다)
csv_file = 'malicious_phish.csv'

print("🔍 파일 확인 중...")
if not os.path.exists(csv_file):
    print("❌ [오류] 파일을 찾을 수 없습니다!")
    print("왼쪽 폴더 아이콘을 눌러 파일이 있는지 확인하고, 이름을 다시 확인해 보세요.")
    print("현재 폴더에 있는 파일들:", os.listdir('/content'))
else:
    print("📖 파일을 찾았습니다! 읽어오는 중...")
    df = pd.read_csv(csv_file)

    # 2. 데이터 가공 (10만 개 학습)
    # 데이터셋의 실제 컬럼명이 'url'과 'type'인지 확인 후 진행합니다.
    df_sample = df.sample(n=100000, random_state=42)

    print("🧠 AI가 악성 패턴을 정밀 분석 중입니다... (약 1~2분 소요)")
    # extract_final_features_final 함수가 위에 이미 선언되어 있어야 합니다.
    X = pd.DataFrame([extract_final_features_final(u) for u in df_sample['url']])
    y = df_sample['type'].apply(lambda x: 0 if x == 'benign' else 1)

    # 3. 학습 및 저장
    model = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
    X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model.fit(X_train, y_train)
joblib.dump(model, "smart_model.pkl")

print("✅ [성공] 학습 완료! 이제 smart_model.pkl이 생성되었습니다.")

def get_gnn_inspired_features(url):
    url = str(url).lower()
    features = []

    # 1. 노드 간의 거리 (도메인과 경로의 관계)
    parts = url.split('/')
    domain = parts[2] if len(parts) > 2 else ""
    path = "/".join(parts[3:]) if len(parts) > 3 else ""
    features.append(len(path) / len(domain) if len(domain) > 0 else 0)

    # 2. 도메인 계층 구조 (서브도메인 노드 개수)
    subdomains = domain.split('.')
    features.append(len(subdomains)) # 노드 개수가 많을수록(꼬리가 길수록) 위험

    # 3. 위험 노드(TLD) 존재 여부 - 관계의 핵심
    suspicious_tld = ['.cc', '.xyz', '.tk', '.ml', '.top']
    features.append(1 if any(tld in domain for tld in suspicious_tld) else 0)

    # 4. 연결자(Edge)의 특징 (특수문자 관계)
    # 악성 사이트는 노드 사이를 '.', '-' 외에 '@', '_' 등으로 억지 연결함
    features.append(url.count('@') + url.count('_'))

    # (기존 기본 수치들 추가)
    features.append(len(url))
    features.append(url.count('.'))

    return features

import pandas as pd
import math
import re
import os
from sklearn.ensemble import RandomForestClassifier

# [1] 엔트로피 계산 최적화
def get_entropy(text):
    if not text: return 0
    probs = [text.count(c) / len(text) for c in set(text)]
    return -sum(p * math.log2(p) for p in probs)

# [2] 특징 추출 함수 (연산량 최적화 버전)
def extract_final_features(url):
    url = str(url).lower()

    # 기본 분해
    parts = url.split('://')
    domain_path = parts[-1].split('/')
    domain = domain_path[0]
    path = "/".join(domain_path[1:]) if len(domain_path) > 1 else ""

    # 특징 리스트 초기화
    f = []

    # 1. 구조적 특징
    f.append(domain.count('.')) # 점 개수
    f.append(len(path) / len(domain) if len(domain) > 0 else 0)

    # 2. TLD 위험도 (Set 사용으로 속도 향상)
    suspicious_tlds = {'.cc', '.xyz', '.tk', '.ml', '.top', '.ga', '.cf', '.site', '.lat', '.shop', '.cn', '.cyou'}
    f.append(1 if any(tld in domain for tld in suspicious_tlds) else 0)

    # 3. 하이픈 (3개 이상일 때만 페널티 - 오탐 방지 핵심)
    h_count = url.count('-')
    f.append(h_count if h_count > 2 else 0)

    # 4. 엔트로피
    f.append(get_entropy(domain))

    # 5. 🔥 브랜드 사칭 점수 (Typosquatting 저격)
    brands = ['google', 'naver', 'allegro', 'smbc', 'paypal', 'amazon', 'apple', 'kakao']
    brand_score = 0
    for b in brands:
        if b in domain:
            if not (domain.endswith(f"{b}.com") or domain.endswith(f"{b}.co.kr") or domain.endswith(f"{b}.net")):
                brand_score += 5
    f.append(brand_score)

    # 6. 위험 키워드 (도메인과 경로 차별화)
    danger_kw = ['login', 'verify', 'update', 'account', 'mycard']
    dk_score = sum(3 for k in danger_kw if k in domain) + sum(0.5 for k in danger_kw if k in path)
    f.append(dk_score)

    # 7. 기본 길이 및 프로토콜
    f.append(len(url))
    f.append(1 if url.startswith('http://') else 0)

    return f

# [3] 데이터 로드 및 학습 (속도 최적화 버전)
csv_file = '/content/malicious_phish.csv'
if not os.path.exists(csv_file):
    print("❌ 파일을 확인해주세요.")
else:
    print("📖 데이터 샘플링 및 특징 추출 시작...")
    df = pd.read_csv(csv_file)
    df['label'] = df['type'].apply(lambda x: 0 if x == 'benign' else 1)

    # 데이터 양을 10만 개에서 4만 개로 줄여도 충분히 강력합니다 (속도를 위해 조정)
    df_benign = df[df['label'] == 0].sample(n=20000, random_state=42)
    df_malicious = df[df['label'] == 1].sample(n=min(len(df[df['label'] == 1]), 20000), random_state=42)
    df_balanced = pd.concat([df_benign, df_malicious])

    # 🔥 속도 향상의 핵심: apply 대신 리스트 컴프리헨션 사용
    print("🧠 특징 추출 중... (이 단계가 가장 오래 걸립니다)")
    X = [extract_final_features(u) for u in df_balanced['url']]
    y = df_balanced['label']

    print("🚀 모델 학습 중...")
    model = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=42)
    X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model.fit(X_train, y_train)
print("✅ 준비 완료!")

# [4] 결과 판단 임계값 조정 (0.4 -> 0.7)
# (이후 루프에서 prob > 0.7 일 때만 [DANGER]로 표시하도록 수정하세요)

# [3] 데이터 로드 및 최신 데이터 주입 학습
csv_file = '/content/malicious_phish.csv'

# 1. 파일이 있는지 먼저 확인 (이 if문이 있어야 아래 else가 작동함)
if not os.path.exists(csv_file):
    print("❌ 파일을 찾을 수 없습니다! 왼쪽 폴더에 malicious_phish.csv를 업로드해주세요.")
else:
    print("📖 데이터 로딩 및 최신 악성 URL 주입 중...")
    df = pd.read_csv(csv_file)
    df['label'] = df['type'].apply(lambda x: 0 if x == 'benign' else 1)

    # 2. 🔥 AI가 놓치고 있는 최신 악성 URL 강제 학습 리스트
    extra_malicious = [
        "https://sellerapp.allegroshop.cyou/",
        "http://nexon-gift-event.xyz/",
        "https://login-naver-security.top/",
        "https://mycard-smbc-co-jp.com/login",
        "https://shop.allegroshop.cyou/",
        "https://euts-carpetcleaning.com/lonos" # 예시: 오탐 방지를 위해 학습 데이터에 명시 가능
    ]

    # 추가 데이터를 데이터프레임으로 변환
    extra_df = pd.DataFrame({'url': extra_malicious, 'label': [1] * len(extra_malicious)})

    # 3. 기존 데이터와 합치기
    df_combined = pd.concat([df[['url', 'label']], extra_df], ignore_index=True)

    # 4. 데이터 균형 맞추기 (학습 속도를 위해 샘플링 갯수 최적화)
    # 정상 데이터 3만개 + 악성 데이터 전체
    df_benign = df_combined[df_combined['label'] == 0].sample(n=30000, random_state=42)
    df_malicious = df_combined[df_combined['label'] == 1]
    df_balanced = pd.concat([df_benign, df_malicious])

    print(f"🧠 {len(extra_malicious)}개의 타겟 데이터를 포함해 특징 추출 중...")

    # 특징 추출 (extract_final_features 함수가 이 코드보다 위에 선언되어 있어야 함)
    X = [extract_final_features(u) for u in df_balanced['url']]
    y = df_balanced['label']

    print("🚀 AI 엔진 재학습 시작... (약 1분 소요)")
    model = RandomForestClassifier(n_estimators=150, n_jobs=-1, random_state=42)
    X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model.fit(X_train, y_train)
print("✅ [재학습 성공] 이제 분석 준비가 끝났습니다!")

import pandas as pd
import os

# 1. 원본 데이터 로드
csv_file = '/content/malicious_phish.csv'

if not os.path.exists(csv_file):
    print("❌ 파일을 찾을 수 없습니다! 'malicious_phish.csv'를 업로드했는지 확인하세요.")
else:
    df = pd.read_csv(csv_file)
    # type 컬럼을 0(정상), 1(악성)로 변환
    df['label'] = df['type'].apply(lambda x: 0 if x == 'benign' else 1)

    # 2. 🔥 AI가 놓치는 최신 악성 URL 리스트 (강제 주입용)
    extra_malicious_urls = [
        "https://sellerapp.allegroshop.cyou/",
        "http://nexon-gift-event.xyz/",
        "https://login-naver-security.top/",
        "https://mycard-smbc-co-jp.com/login",
        "https://shop.allegroshop.cyou/",
        "https://allegro-lokalnie.91287167261627218.asia/"
    ]

    # 추가 데이터를 데이터프레임으로 변환
    extra_df = pd.DataFrame({
        'url': extra_malicious_urls,
        'label': [1] * len(extra_malicious_urls)
    })

    # 3. 🚀 [핵심] 데이터 합치기 (df_combined 정의)
    # 여기서 df_combined를 먼저 만들어야 아래에서 NameError가 안 납니다!
    df_combined = pd.concat([df[['url', 'label']], extra_df], ignore_index=True)

    # 4. 데이터 균형 맞추기 (1:1 비율 샘플링)
    mal_count = len(df_combined[df_combined['label'] == 1])

    # 정상 데이터 중에서 악성 데이터 개수만큼만 랜덤 추출
    df_benign = df_combined[df_combined['label'] == 0].sample(n=mal_count, random_state=42)
    df_malicious = df_combined[df_combined['label'] == 1]

    # 최종 학습 데이터셋 생성
    df_balanced = pd.concat([df_benign, df_malicious])

    print(f"✅ 데이터 합치기 및 균형 완료!")
    print(f"📊 총 데이터: {len(df_balanced)}개 (정상: {mal_count} / 악성: {mal_count})")

# 악성 데이터 개수에 맞춰 정상 데이터를 샘플링 (1:1 비율)
mal_count = len(df_combined[df_combined['label'] == 1])
df_benign = df_combined[df_combined['label'] == 0].sample(n=mal_count, random_state=42)
df_malicious = df_combined[df_combined['label'] == 1]

df_balanced = pd.concat([df_benign, df_malicious])
print(f"✅ 데이터 균형 완료! (정상: {mal_count} / 악성: {mal_count})")

def extract_final_features(url):
    url = str(url).lower()

    # 기본 분해
    parts = url.split('://')
    domain_path = parts[-1].split('/')
    domain = domain_path[0]
    path = "/".join(domain_path[1:]) if len(domain_path) > 1 else ""
    subdomains = domain.split('.')

    f = []

    # 1. 도메인 구조 (점 개수가 많으면 낚시 도메인일 확률 높음)
    f.append(len(subdomains))

    # 2. TLD 위험도 (매우 강력하게 적용)
    # .com, .net, .kr 등 정상 TLD면 0, 아니면 1
    safe_tlds = ('.com', '.net', '.org', '.kr', '.jp', '.co.kr', '.co.jp')
    is_unsafe_tld = 0 if any(domain.endswith(tld) for tld in safe_tlds) else 1
    f.append(is_unsafe_tld)

    # 3. 하이픈(-)과 키워드의 결합 (악성 종특)
    # euts-carpetcleaning 처럼 비즈니스 명칭은 봐주고, login, account 등이 섞이면 점수 폭등
    bad_keywords = ['login', 'verify', 'account', 'update', 'secure', 'mycard', 'seller', 'smbc', 'allegro']
    keyword_in_domain = any(k in domain for k in bad_keywords)
    f.append(1 if (keyword_in_domain and (is_unsafe_tld or '-' in domain)) else 0)

    # 4. 엔트로피 (무작위 문자열)
    f.append(get_entropy(domain))

    # 5. 브랜드 사칭 거리 측정 (가장 중요한 킬러 로직)
    # 브랜드명이 도메인 중간에 '끼어' 있는 경우 점수 대폭 상승
    brand_score = 0
    brands = ['smbc', 'allegro', 'nexon', 'naver', 'google', 'kakao']
    for b in brands:
        if b in domain:
            # 공식 도메인이 아닌데 브랜드명이 포함된 경우 (예: mycard-smbc)
            if not (domain.endswith(f"{b}.com") or domain.endswith(f"{b}.co.jp") or domain.endswith(f"{b}.jp")):
                brand_score += 10 # 매우 강력한 가중치
    f.append(brand_score)

    # 6. 경로(Path) 복잡도 vs 도메인 길이 비율
    # 정상 사이트는 경로가 길고, 피싱은 도메인이 복잡한 경향이 있음
    f.append(len(path) / (len(domain) + 1))

    # 7. 디지털 집계
    digits = re.findall(r'\d', url)
    f.append(len(digits) / len(url) if len(url) > 0 else 0)

    return f

# 학습 데이터 준비 시 추가
extra_benign = [
    "https://euts-carpetcleaning.com",
    "https://www.google.com/search?q=cleaning",
    "https://www.amazon.com/gp/cart/view.html",
    "https://github.com/trending"
]
# ... 이 데이터를 Label 0으로 해서 학습 데이터에 50번씩 복사해서 넣으세요 (가중치 학습)

def extract_final_features(url):
    url = str(url).lower()
    domain = url.split('://')[-1].split('/')[0]
    path = "/".join(url.split('://')[-1].split('/')[1:])

    f = []
    # 1. 브랜드 사칭 강제 저격 (가장 강력한 가중치)
    brands = ['allegro', 'smbc', 'nexon', 'naver', 'card', 'bank', 'login']
    brand_score = 0
    for b in brands:
        if b in domain:
            # 공식 사이트가 아니면 점수 폭탄 (가중치 20)
            if not (domain.endswith(f'{b}.com') or domain.endswith(f'{b}.pl') or domain.endswith(f'{b}.co.jp')):
                brand_score += 20
    f.append(brand_score)

    # 2. 위험 TLD 저격 (.cyou, .asia, .top 등)
    danger_tlds = ['.cyou', '.asia', '.top', '.xyz', '.work', '.click', '.info']
    f.append(15 if any(domain.endswith(tld) for tld in danger_tlds) else 0)

    # 3. 무작위 숫자 패턴 (allegro-lokalnie.912871...)
    digits = re.findall(r'\d', domain)
    f.append(len(digits) if len(digits) > 5 else 0)

    # 4. 하이픈(-) 남용
    f.append(domain.count('-') * 5)

    # 5. 기존 엔트로피 및 길이
    f.append(get_entropy(domain) * 10)
    f.append(len(url))

    return f

# [오답 노트 강제 주입]
fail_urls = [
    "https://shop.allegroshop.cyou/",
    "https://sellerapp.allegroshop.cyou/",
    "https://mycard-smbc-co-jp.com/login",
    "https://allegro-lokalnie.91287167261627218.asia/"
]

# 위 URL들을 학습 데이터에 100번씩 복사해서 넣습니다. (편중 학습 시키기)
extra_malicious = pd.DataFrame({
    'url': fail_urls * 100,
    'label': [1] * (len(fail_urls) * 100)
})
df_balanced = pd.concat([df_balanced, extra_malicious], ignore_index=True)

def collect_with_source(target=500):
    all_data = []

    print("🚀 [블랙리스트] 출처별 수집 시작...")

    # OpenPhish
    try:
        res = requests.get("https://openphish.com/feed.txt", timeout=5)
        urls = [u.strip() for u in res.text.split('\n') if u.strip()]
        for u in urls:
            if len(all_data) < target:
                all_data.append({"url": u, "label": 1, "source": "OpenPhish"})
    except:
        print("⚠️ OpenPhish 실패")

    # URLhaus
    if len(all_data) < target:
        try:
            res = requests.get("https://urlhaus.abuse.ch/downloads/text/", timeout=5)
            urls = [u.strip() for u in res.text.split('\n') if u.strip() and not u.startswith('#')]
            for u in urls:
                if len(all_data) < target:
                    all_data.append({"url": u, "label": 1, "source": "URLhaus"})
        except:
            print("⚠️ URLhaus 실패")

    black_df = pd.DataFrame(all_data)

    print("🚀 [화이트리스트] 생성 시작...")
    real_white_df = get_real_whitelist(2000)

    total_df = pd.concat([black_df, real_white_df], ignore_index=True)

    black_df.to_csv("Blacklist/blacklist_with_source.csv", index=False)
    real_white_df.to_csv("Whitelist/whitelist_with_source.csv", index=False)
    total_df.to_csv("gnn_total_dataset.csv", index=False)

    return total_df

import pandas as pd
import joblib
import re
import os
import math
from sklearn.ensemble import RandomForestClassifier

# [1] 문자열 무질서도(엔트로피) 계산
def get_entropy(text):
    if not text or len(text) == 0: return 0
    probs = [text.count(c) / len(text) for c in set(text)]
    return -sum(p * math.log2(p) for p in probs)

# [2] 12가지 통합 특징 추출 엔진 (핵심 로직)
def extract_final_features(url):
    url = str(url).lower().strip()

    # URL 구조 분해
    parts = url.split('://')
    protocol = parts[0] if len(parts) > 1 else "none"
    domain_path = parts[-1].split('/')
    domain = domain_path[0]
    path = "/".join(domain_path[1:]) if len(domain_path) > 1 else ""
    subdomains = domain.split('.')

    features = [] # <--- 여기서 리스트를 생성합니다

    # 1. 구조적 특징
    features.append(len(subdomains)) # 계층 깊이
    features.append(len(path) / (len(domain) + 1)) # 경로/도메인 비율

    # 2. 위험 TLD 체크
    suspicious_tld = ['.cc', '.xyz', '.tk', '.ml', '.top', '.ga', '.cf', '.site', '.lat', '.shop', '.cn', '.online', '.cyou', '.asia', '.sbs']
    features.append(1 if any(tld in domain for tld in suspicious_tld) else 0)

    # 3. 비정상 연결 기호
    features.append(url.count('-') + url.count('@') + url.count('_') + url.count('='))

    # 4. 플랫폼 기생 여부
    platforms = ['wix', 'google', 'github', 'vercel', 'firebase', 'pages', 'notion']
    features.append(1 if any(p in domain for p in platforms) else 0)

    # 5. 도메인 엔트로피
    ent = get_entropy(domain)
    features.append(ent)

    # 6. 위험 키워드 가중치
    danger_keywords = ['whatsapp', 'allegro', 'utente', 'bnl', 'it-', 'login', 'bridge', 'verify', 'update', 'account', 'smbc', 'stpmex']
    features.append(sum(1 for k in danger_keywords if k in url))

    # 7. 기본 수치
    features.append(len(url))
    features.append(1 if protocol == 'http' else 0)
    digits = re.findall(r'\d', url)
    features.append(len(digits) / (len(url) + 1))

    # 8. 킬러 로직 (복합 관계 분석)
    path_complexity = path.count('/')
    features.append(1 if (any(tld in domain for tld in suspicious_tld)) and path_complexity >= 2 else 0)
    features.append(1 if (len(domain.split('-')) > 1 or ent > 3.8) else 0)

    return features # <--- 이제 에러 없이 반환됩니다!

# [3] 모델 학습 및 저장
def train_model():
    # 파일 경로 확인 (코랩용)
    csv_file = '/malicious_phish.csv'

    if not os.path.exists(csv_file):
        print(f"❌ 파일을 찾을 수 없습니다: {csv_file}")
        return

    print("📖 데이터 로드 중...")
    df = pd.read_csv(csv_file)
    df['label'] = df['type'].apply(lambda x: 0 if x == 'benign' else 1)

    # 데이터 균형 맞추기 (5만 개 샘플링)
    df_benign = df[df['label'] == 0].sample(n=25000, random_state=42)
    df_malicious = df[df['label'] == 1].sample(n=min(len(df[df['label'] == 1]), 25000), random_state=42)
    df_balanced = pd.concat([df_benign, df_malicious])

    print("🧠 AI 엔진 학습 중... (약 1분 소요)")
    X = pd.DataFrame([extract_final_features(u) for u in df_balanced['url']])
    y = df_balanced['label']

    model = RandomForestClassifier(n_estimators=100, n_jobs=-1, class_weight='balanced', random_state=42)
    X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model.fit(X_train, y_train)

    # 모델 저장
joblib.dump(model, "gnn_model.pkl")
print("✅ 모델 저장 완료: gnn_model.pkl")

if __name__ == "__main__":
    train_model()

import requests

def get_latest_malicious_urls(limit=500):
    print("🚀 실시간 악성 URL 수집 중 (OpenPhish)...")
    try:
        # OpenPhish의 무료 텍스트 피드 사용
        res = requests.get("https://openphish.com/feed.txt", timeout=5)
        urls = [u.strip() for u in res.text.split('\n') if u.strip()]
        return urls[:limit]
    except Exception as e:
        print(f"⚠️ 수집 실패: {e}")
        return []

# 실시간 데이터 확보
live_malicious_urls = get_latest_malicious_urls(500)
live_df = pd.DataFrame({'url': live_malicious_urls, 'label': [1] * len(live_malicious_urls)})

# [오답 노트] AI가 놓쳤던 실제 악성 URL들
fail_urls = [
    "https://shop.allegroshop.cyou/",
    "https://sellerapp.allegroshop.cyou/",
    "https://login-naver-security.top/",
    "https://mycard-smbc-co-jp.com/login"
]

# 위 URL들을 100번씩 복제해서 가중치를 높임
extra_malicious = pd.DataFrame({
    'url': fail_urls * 100,
    'label': [1] * (len(fail_urls) * 100)
})

def extract_features_url(url):
    import re
    features = {}

    features['url_len'] = len(url)
    features['dot_count'] = url.count('.')
    features['hyphen_count'] = url.count('-')
    features['count_at'] = url.count('@')        # 추가
    features['count_slash'] = url.count('/')     # 추가
    features['digit_ratio'] = len(re.findall(r'\d', url)) / len(url)
    features['is_https'] = 1 if url.startswith('https') else 0

    # 🔥 부족한 2개 채워주기 (학습 맞추기용)
    features['dummy1'] = 0
    features['dummy2'] = 0

    return features

# 1. 학습할 때 썼던 데이터프레임의 컬럼을 직접 리스트로 만드세요
# 예: selected_features = ['url_len', 'dot_count', ... ] 총 10개
selected_features = [
    'feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5',
    'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_10'
]

# 2. 그런 다음 아래 함수를 사용하세요
def get_prediction(u):
    raw_dict = extract_final_features(u)
    # 필요한 10개만 순서대로 추출
    feature_values = [raw_dict[k] for k in selected_features]

    # 모델에 넣기 위해 2차원 배열 형태로 변환
    return model.predict_proba([feature_values])[0][1]

def extract_final_features(url):
    # 1. 각 변수에 실제 값을 계산해서 넣으세요
    f1 = len(url)
    f2 = url.count('.')
    f3 = url.count('-')
    f4 = url.count('/')  # 예시: 슬래시 개수
    f5 = url.count('?')  # 예시: 물음표 개수
    f6 = 1 if "https" in url else 0
    f7 = url.count('=')
    f8 = url.count('@')
    f9 = url.count('_')
    f10 = sum(c.isdigit() for c in url) # 숫자 개수
    f11 = url.count('%')
    f12 = url.count('&')

    # 2. 정의된 변수들을 리스트로 반환
    return [f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12]

# 기존 데이터 + 실시간 데이터 + 오답 노트 합치기
df_final = pd.concat([df_balanced, live_df, extra_malicious], ignore_index=True)

print(f"📊 최종 학습 데이터 개수: {len(df_final)}개")

# 재학습 진행
X = pd.DataFrame([extract_final_features(u) for u in df_final['url']])
y = df_final['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model.fit(X_train, y_train)
print("✅ 최신 악성 데이터 학습 완료!")

# 1. 대상 URL 정의
u = "http://example.com/login-code"

# 2. URL에서 경로(path) 추출 (이 부분이 있어야 에러가 안 납니다)
# '://' 뒤를 가져온 후 첫 번째 '/' 이후의 모든 문자열을 가져옵니다.
path = '/' + '/'.join(u.split('://')[-1].split('/')[1:]).lower()

# 3. 블랙리스트 확인 로직
path_blacklist = ['lonos', 'login-code', 'stpmex']

if any(pb in path for pb in path_blacklist):
    prob = 1.0
    reason = "🚩 경로 내 차단 키워드 발견 (Blacklist)"
    print(reason)

import pandas as pd
import joblib
import re
import os
import math
from sklearn.ensemble import RandomForestClassifier

# [1] 통합 특징 추출 엔진 (총 12개 특징)
def get_entropy(text):
    if not text or len(text) == 0: return 0
    probs = [text.count(c) / len(text) for c in set(text)]
    return -sum(p * math.log2(p) for p in probs)

def extract_final_features(url):
    url = str(url).lower().strip()
    features = []

    parts = url.split('://')
    protocol = parts[0] if len(parts) > 1 else "none"
    domain_path = parts[-1].split('/')
    domain = domain_path[0]
    path = "/".join(domain_path[1:]) if len(domain_path) > 1 else ""
    subdomains = domain.split('.')

    # 1~12번 특징 추출
    features.append(len(subdomains)) # 1
    features.append(len(path) / len(domain) if len(domain) > 0 else 0) # 2
    suspicious_tld = ['.cc', '.xyz', '.tk', '.ml', '.top', '.ga', '.cf', '.site', '.lat', '.shop', '.cn', '.online', '.cyou', '.asia', '.sbs']
    features.append(1 if any(tld in domain for tld in suspicious_tld) else 0) # 3
    features.append(url.count('-') + url.count('@') + url.count('_') + url.count('=')) # 4
    platforms = ['wix', 'google', 'github', 'vercel', 'firebase', 'pages', 'notion']
    is_on_platform = 1 if any(p in domain for p in platforms) else 0
    features.append(is_on_platform) # 5
    ent = get_entropy(domain)
    features.append(ent) # 6
    danger_keywords = ['whatsapp', 'allegro', 'utente', 'bnl', 'it-', 'login', 'bridge', 'verify', 'update', 'account', 'smbc', 'stpmex']
    features.append(sum(1 for k in danger_keywords if k in url)) # 7
    features.append(len(url)) # 8
    features.append(1 if protocol == 'http' else 0) # 9
    digits = re.findall(r'\d', url)
    features.append(len(digits) / len(url) if len(url) > 0 else 0) # 10
    path_complexity = path.count('/')
    features.append(1 if (any(tld in domain for tld in suspicious_tld)) and path_complexity >= 2 else 0) # 11
    features.append(1 if is_on_platform and (len(domain.split('-')) > 1 or ent > 3.8) else 0) # 12

    return features

# [추가] 화이트리스트 및 블랙리스트 정의
whitelist = ['google.com', 'naver.com', 'daum.net', 'github.com', 'apple.com', 'microsoft.com', 'tistory.com']
blacklist = ['bit.ly-login', 'secure-update-account', 'verify-smbc']
path_blacklist = ['/login', '/verify', '/update', '/account']

# 만약 train_test_split 에러가 난다면 이 import도 확인하세요
from sklearn.model_selection import train_test_split

# [2] 데이터 로드 및 학습 (오탐 방지 최적화 버전)
if not os.path.exists(csv_file):
    print("❌ 파일을 찾을 수 없습니다!")
else:
    df = pd.read_csv(csv_file)
    df['label'] = df['type'].apply(lambda x: 0 if x == 'benign' else 1)

    # 정상 데이터를 악성 데이터보다 1.5배 더 많이 넣어서 '정상'의 기준을 넓혀줍니다.
    df_benign = df[df['label'] == 0].sample(n=45000, random_state=42)
    df_malicious = df[df['label'] == 1].sample(n=30000, random_state=42)
    df_balanced = pd.concat([df_benign, df_malicious])

    print("🧠 AI를 유연하게 재학습 중... (max_depth 제한)")
    X = pd.DataFrame([extract_final_features(u) for u in df_balanced['url']])
    y = df_balanced['label']

    # 🔥 max_depth=8: AI가 너무 꼬치꼬치 따지지 않게 제한합니다.
    # min_samples_leaf=10: 너무 지엽적인 특징은 무시하게 합니다.
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=8,
        min_samples_leaf=10,
        n_jobs=-1,
        class_weight='balanced',
        random_state=42
    )
    X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model.fit(X_train, y_train)
print("✅ 유연한 학습 완료!")

# [3] 테스트 루프 (지능형 판정 버전)
while True:
    u = input("\n🔍 스캔할 URL 입력 (종료: q): ").strip()
    if u.lower() == 'q': break
    if not u: continue

    url_no_proto = u.split('://')[-1]
    domain = url_no_proto.split('/')[0].lower()
    path = "/".join(url_no_proto.split('/')[1:]).lower()

    # AI 점수 추출
    feat_full = [extract_final_features(u)]
    prob_full = model.predict_proba(feat_full)[0][1]

    feat_domain = [extract_final_features("http://" + domain)]
    prob_domain = model.predict_proba(feat_domain)[0][1]

    # 기본 점수는 평균을 내서 극단적인 판정을 막습니다.
    prob = (prob_domain * 0.5) + (prob_full * 0.5)

    # --- 지능형 판정 가중치 ---
    # 1. 화이트리스트 도메인에 대한 강력한 면죄부
    if any(w in domain for w in whitelist):
        # 구글/네이버 같은 곳은 AI 점수가 아무리 높아도 80%를 깎아버립니다.
        prob = prob * 0.2
        reason = "✅ 화이트리스트 기반 안전 승인"

    # 2. 블랙리스트는 가차없이 차단
    elif any(b in domain for b in blacklist) or any(pb in path for pb in path_blacklist):
        prob = 1.0
        reason = "🚩 블랙리스트 차단"
    else:
        reason = "🤖 AI 패턴 분석 진행"

    final_score = prob * 100
    # 위험 기준점을 70점으로 대폭 상향 (확실할 때만 경고)
    threshold = 70.0

    print("-" * 60)
    print(f"📡 분석 대상: {u}")
    print(f"🚨 위험 지수: {final_score:.1f}% ({reason})")
    print(f"🚩 결과: {'[위험]' if final_score >= threshold else '[안전]'}")
    print("-" * 60)
